### ISSUE TITLE
Incorrect SQL on due_date

### ISSUE THREAD

**Issue by Asfolny** [vr0n/talist#4] opened 2020-08-07 13:00 UTC
`db.exec(sql"CREATE TABLE items ( id INTEGER PRIMARY KEY, name VARCHAR(500) NOT NULL , label VARCHAR(100) NOT NULL, due_date CHECK (date(due_date) IS NOT NULL )")`

Well first of all it's easier to read when you format it like this
```nim
db.exec(sql"""CREATE TABLE items (
  id INTEGER PRIMARY KEY,
  name VARCHAR(500) NOT NULL,
  label VARCHAR(100) NOT NULL,
  due_date CHECK (date(due_date) IS NOT NULL
)""")
```
And then the issue is also immediately clear, the `CHECK` is opened, but never actually closed again.

**Comment by Asfolny** [comment] 2020-08-07 14:11
Not that fixing it would help much, the check is executed on each and every insert, and when there is no due_date, the result will be null too

A more correct constraint would be `CHECK (due_date IS NULL OR date(due_date) IS NOT NULL)`

Furthermore, according to the sqlite3 documentation, `date` is equal to `strftime('%Y-%m-%d', ...)` ([link](https://www.sqlite.org/lang_datefunc.html)), meaning that the only format that is valid under this constraint, is %Y-%m-%d (or YYYY-MM-DD), so your format of MM/DD/YYYY causes the constraint to fail, and the whole application to break

Important note that the format for sqlite doesn't seem negotiable, only YYYY-MM-DD is valid, so to get your format, you could output it with `strftime(%m/%d/%Y)` but to have the same as input, you would have to split on /, and hardcode the logic for input (first value is month, second is day, third is year, reformat to the valid format above and update in the db)

Now that might be a separate issue, but failing this just stops the application, a `try...catch` here would've been better, so you can tell people that it's the due_date that's wrongly formatted

**Comment by Asfolny** [comment] 2020-08-07 14:32
So it's pretty confusing how it actually does work within the v1 release video, because, it shouldn't
But then again, neither should the insert work, nor the update because of the CHECK... maybe github is a few versions back, and maybe there's a different sqlite version/variant in play here

My sqlite version is 3.32.3

**Comment by vr0n** [comment] 2020-08-07 16:54
Hmmm... that's my sqlite3 version as well. 

Can you link the error you're getting? I literally can't get mine to crash even by inserting incorrect date formats.

**Comment by Asfolny** [comment] 2020-08-07 17:10
```
Enter the number of the item you want to add a due date to (or 'Enter' to cancel):
>> 0
Enter the date this item is due in MM/DD/YYYY format:
>> 09-20-2020
... (stacktrace here)
Error: unhandled exception: CHECK constraint failed: items [DbError]
```

From the documentation:
```
A time string can be in any of the following formats:

YYYY-MM-DD
YYYY-MM-DD HH:MM
YYYY-MM-DD HH:MM:SS
YYYY-MM-DD HH:MM:SS.SSS
YYYY-MM-DDTHH:MM
YYYY-MM-DDTHH:MM:SS
YYYY-MM-DDTHH:MM:SS.SSS
HH:MM
HH:MM:SS
HH:MM:SS.SSS
now
DDDDDDDDDD
```

Mind you this is an error after deleting the db and re-creating with `due_date CHECK (due_date IS NULL OR date(due_date) IS NOT NULL)`

From the base, I get `Error: unhandled exception: incomplete input [DbError]` on startup

And with the missing parenthesis I get 
```Enter the new item:
>> Something
... (stacktrace)
Error: unhandled exception: CHECK constraint failed: items [DbError]
```
Both stacktraces go all the way down to the db_sqlite module from nim, and the errors are purely from the db

**Comment by vr0n** [comment] 2020-08-07 17:31
Ok. I just pushed a new change that validates the date in both SQL and Nim. 

Let me know if that works, and I will close this issue. 

I am still totally baffled at what we are seeing differently. I literally entered "adsfasdfsadfasdf" into the date, and it validated and entered it as a "date." So, the problem is definitely on my end.

**Comment by Asfolny** [comment] 2020-08-07 17:39
Could it be that you didn't delete the db after one of the rounds before you got to the current version?
Since the install only goes if the file doesn't exist, and sqlite doesn't have it's own date type, it just uses text, which can store everything

**Comment by vr0n** [comment] 2020-08-07 17:44
Yep! that was it!

Thank you! Sorry, I am such a programming scrub!

Let me know if the push I just made a few seconds ago works!

**Closed as completed** 2020-08-07 18:04 UTC

**Comment by Asfolny** [comment] 2020-08-07 19:00
It does work, and doesn't crash on invalid input at least
But what's with that sleep 1?

EDIT: oh right, otherwise it discards it... 1s is a bit too long for my taste, but since the entire thing is rendered line per line (as far as I can immediately tell) it'd be hard to just continue asking for input

**Comment by vr0n** [comment] 2020-08-07 21:41
The specific reason for that is to see the error message about the incorrect date format before it gets wiped by the re-draw
